# Data preparation configuration

genome:
  fasta: "data/genome/mm10.fa"
  chrom_sizes: "data/genome/mm10.chrom.sizes"

cell_types:
  - Cardiomyocyte
  - Coronary_EC
  - Fibroblast
  - Macrophage
  - Pericytes

fragments:
  dir: "data"
  pattern: "{cell_type}_downsample.bed"

peaks:
  merged_bed: "data/peaks_downsampled/merged_peaks.bed"
  original_bed: "data/YoungSed_DownSample_Peak.bed"  # original (called on all cells)
  logcpm_celltype: "data/YoungSed_DownSample_Peak_logCPM_CellType.csv"
  logcpm_mouse: "data/YoungSed_DownSample_Peak_logCPM_CellType_Mouse.csv"

bigwig:
  output_dir: "data/bigwig"

specificity:
  tau_specific_threshold: 0.6
  tau_shared_threshold: 0.3
  fdr_threshold: 0.05
  output: "data/peak_annotations.csv"

chromosome_splits:
  test: ["chr8", "chr9"]
  val: ["chr1"]
  train: ["chr2", "chr3", "chr4", "chr5", "chr6", "chr7",
          "chr10", "chr11", "chr12", "chr13", "chr14", "chr15",
          "chr16", "chr17", "chr18", "chr19"]
